stages:          # List of stages for jobs, and their order of execution
  - deploy

deploy_stage:
  stage: deploy
  image: docker:stable-git
  services:
    - docker:stable-dind
  before_script:
    - docker stop $CI_PROJECT_NAME || true
    - docker rm $CI_PROJECT_NAME || true
    - docker rmi $CI_REGISTRY_IMAGE:latest || true
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker run --name $CI_PROJECT_NAME -d -p 4200:80 $CI_REGISTRY_IMAGE:latest