stages:          # List of stages for jobs, and their order of execution
  - staging

staging_stage:
  stage: staging
  image: docker:stable-git
  services:
    - docker:stable-dind
  before_script:
    - docker stop goodwareui:staging || true
    - docker rm goodwareui:staging || true
    - docker rmi goodwareui:staging || true
  script:
    - docker build -t goodwareui:staging .
    - docker run --name goodwareui:staging -d -p 4202:80 goodwareui:staging
