stages:          # List of stages for jobs, and their order of execution
  - staging

staging_stage:
  stage: staging
  image: docker:stable-git
  services:
    - docker:stable-dind
  before_script:
    - docker stop goodwareui-dev || true
    - docker rm goodwareui-dev || true
    - docker rmi goodwareui-dev:staging || true
  script:
    - docker build -t goodwareui-dev .
    - docker run --name goodwareui-dev -d -p 4202:80 goodwareui-dev:staging
